//ALERTS
export const ALERTS = {
    SET_ALERT: 'SET_ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT'
}

//REGISTRATION
export const REGISTRATION = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL'
}

//LOAD
export const LOAD = {
    LOAD_START: 'LOAD_START',
    LOAD_END: 'LOAD_END'
}

//LOGIN
export const LOGIN = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOAD_USER: 'LOAD_USER',
    LOGOUT_USER: 'LOGOUT_USER'
}

export const DASHBOARD = {
    LOAD_DASHBOARD: 'LOAD_DASHBOARD',
}

//CALCULATOR
export const CALCULATOR_CHANGE = {
    CALCULATE: 'CALCULATE',
    RESET_CALCULATION: 'RESET_CALCULATION',
    COMMISSION: .0025,
    VAT: .12,
    SCCP: 0.0001,
    TRANSACTION_FEE: 0.00005,
    SALES_TAX: 0.006
}

//TRANSACTION
export const TRANSACTION = {
    DIALOG_TRANSACTION: 'DIALOG',
    GET_ALL_TRANSACTION: 'GET_ALL',
    GET_SPECIFIC_TRANSACTION: 'GET_SPECIFIC',
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    EDIT_TRANSACTION: 'EDIT_TRANSACTION',
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
    RESET_ALL_TRANSACTION: 'RESET_ALL',
    SET_TOTALS: 'SET_TOTAL',
    LOAD_START_TRANSACTION: 'LOAD_START_TRANSACTION',
    LOAD_END_TRANSACTION: 'LOAD_END_TRANSACTION'
}